apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
# TODO: Look at HA option (manifests/ha/cluster-install)
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.7.7

# changes to config maps
patchesStrategicMerge:
  #- patch-cm.yaml
