apiVersion: v1
kind: Namespace
metadata:
  name: greeter
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: greeter
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Greeter application greets people.
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/codeformio/*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: greeter
    server: https://kubernetes.default.svc
  # Deny cluster scoped resources.
  clusterResourceWhitelist: []
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-app
  namespace: argocd
spec:
  project: greeter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/codeformio/k8s-greeter-app.git
    path: deploy/non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: greeter

