apiVersion: v1
kind: Namespace
metadata:
  name: greeter
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/codeformio/k8s-greeter-app.git
    path: deploy/non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: greeter
