apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-engine
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: library/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
