apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    path: /deploy/static/provider/kind
    targetRevision: ingress-nginx-2.11.1
