apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ValidGitopsSource
metadata:
  name: valid-gitops-source
spec:
  enforcementaction: dryrun
  match:
    kinds:
    - apiGroups: ["applications.argoproj.io"]
      kinds: ["Application"]
  parameters:
    branchBlocklist: []
