apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-engine
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: library/argocd
