apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-system
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: library/gatekeeper/system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: library/gatekeeper/constraints
