apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./root.yaml
- ./apps/greeter.yaml

patches:
# Ensure branch matches for all cluster-level GitOps apps.
- path: ./patch-gitops-branch.yaml
  target:
    kind: Application
    group: argoproj.io
    labelSelector: app.kubernetes.io/part-of=platform
