apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/codeformio/k8s-greeter-app.git
    targetRevision: local
    path: local
  destination:
    server: https://kubernetes.default.svc
    namespace: greeter
---
